name: ChangeLog
on:
  push:
    - release/**

env:
  VERSION: ${{ github.event.inputs.version }}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: 251311
          private_key: ${{ secrets.TOKEN_EXCHANGE_GH_APP_PRIVATE_KEY }}
          repository: ${{ github.repository }}
          permissions: >-
            {"contents": "read"}
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - name: Check changelog is modified
        run: |
          files=`git diff --name-only | grep -E 'changelog' `
          for file in $files; do
            if [ "$file" = "CHANGELOG.md" ]; then
              exit 0
            fi
          done
          echo ERROR: CHANGELOG has not been updated
          exit 1
