name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version you intend to release (eg x.y.z)

env:
  VERSION: ${{ github.event.inputs.version }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.x'
      - name: Install Buf
        run: make installbuf
      - name: Update Buf Version
        run: make updateversion
      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@ad43dccb4d726ca8514126628bec209b8354b6dd
        with:
          add-paths: .
          commit-message: "updateversion"
          branch: release/v${{env.VERSION}}
          delete-branch: true
          title: "Release ${{env.VERSION}}"
          body: |
            Release prepared for ${{env.VERSION}}
            
            Reminder: Update the changelog
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Slack Notification
        run: |
          jq --null-input '{ text: "BufCLI Release v${{env.VERSION}} has started: ${{ steps.cpr.outputs.pull-request-url }}" }' \
          | curl -sSL -X POST -H 'Content-Type: application/json' -d @- '${{ secrets.SLACK_RELEASE_NOTIFICATION_WEBHOOK }}'
