name: Release

on:
  push:
    tags:
      - v*

env:
  VERSION: ${{ github.ref_name }}
  RELEASE_MINISIGN_PRIVATE_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}
  RELEASE_MINISIGN_PRIVATE_KEY_PASSWORD: ${{ secrets.RELEASE_PRIVATE_KEY_PASSWORD }}

jobs:
  perform:
    runs-on: ubuntu-latest
    steps:
#      - name: Generate token
#        id: generate_token
#        uses: tibdex/github-app-token@v1
#        with:
#          app_id: 251311
#          private_key: ${{ secrets.TOKEN_EXCHANGE_GH_APP_PRIVATE_KEY }}
#          repository: ${{ github.repository }}
#          permissions: >-
#            {"contents": "write", "pull_requests": "write"}
      - name: Checkout repository code
        uses: actions/checkout@v3
#        with:
#          token: ${{ steps.generate_token.outputs.token }}
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.x'
#      - name: Create assets
#        run: make bufrelease
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        id: ghr
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true # change to the CHANGELOG somehow
          working-directory: ${{github.workspace}}/.build/release/buf/assets
          files: |
            $(find .)
#      - name: Slack Notification
#        run: |
#          jq --null-input '{ text: "BufCLI Release v${{env.VERSION}} is complete: ${{ steps.ghr.outputs.url }}" }' \
#          | curl -sSL -X POST -H 'Content-Type: application/json' -d @- '${{ secrets.SLACK_RELEASE_NOTIFICATION_WEBHOOK }}'
