name: Release

on:
  pull_request:
    types: [closed]

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release')
    steps:
      - name: Split branch name
        env:
          BRANCH: ${{ github.ref_name }}
        run: echo "VERSION=v${BRANCH##*/}" >> $GITHUB_STATE
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Tag Release
        run: |
          git config --global user.name "abc"
          git config --global user.email "abc@example.com"
          git tag -d ${{env.VERSION}} 2> /dev/null || echo 'local ref does not exist'
          git push origin :${{env.VERSION}} 2> /dev/null || echo 'remote ref does not exist'
          git tag ${{env.VERSION}}
          git push origin ${{env.VERSION}}
